#!/sbin/runscript
# Copyright 2015 Nicolas Heine

depend() {
        after sshd
        need net
        need localmount
}

start() {
        ebegin "Starting gitlab-ci-multi-runner"
        start-stop-daemon --start -b -u @USER@ --chdir /var/tmp/gitlab-ci-multi-runner --pidfile /var/run/gitlab-ci-multi-runner.pid -1 /dev/null -2 /dev/null --make-pidfile \
                --exec /opt/gitlab-ci-multi-runner/gitlab-ci-multi-runner -- run
        eend $?
}

stop() {
        ebegin "Stopping gitlab-ci-multi-runner"
        start-stop-daemon --stop --pidfile /var/run/gitlab-ci-multi-runner.pid
        eend $?
}
