stages:
  - check
  - deploy

Repoman:
  stage: check
  script:
    - repoman -x -p

pages:
  stage: deploy
  only:
    - master
  script:
    - mkdir .public
    - mv * .public
    - mv .public public
  artifacts:
    paths:
      - public
