on: [push]
jobs:
  pkgcheck:
    runs-on: docker
    container:
      image: gittr.ch/linux/pkgcheck:latest
    steps:
      - name: Checkout repository
        uses: https://gittr.ch/linux/forgejo-actions/checkout@v0.2
      - name: Run repository checks
        run: pkgcheck --color true scan --exit error,style --net .
